import Head from "next/head";
// import { Inter } from "next/font/google";
import { Box } from "@mui/material";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useEffect, useState } from "react";
import { erc20ABI, useAccount, useContract, useSigner } from "wagmi";
import { useRouter } from "next/router";

export default function Home() {
  const [state] = useState(0);
  const { data: signer } = useSigner();
  const router = useRouter();
  const { isConnected } = useAccount();

  useEffect(() => {
    if (!isConnected) return;
    router.push("/panel");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isConnected]);

  const contract = useContract({
    address: "0x07865c6E87B9F70255377e024ace6630C1Eaa37F",
    abi: erc20ABI,
  });

  useEffect(() => {
    if (state === 1) {
      const getAllowance = async () => {
        if (!contract) {
          return;
        }
        if (!signer) {
          return;
        }
        // const amount = ethers.utils.parseEther("10000000");
        // const token1Allowance = await contract
        //   ?.connect(signer)
        //   .approve("0x3ff417dACBA7F0bb7673F8c6B3eE68D483548e37", amount);
      };
      getAllowance();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [state]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Button variant="contained" onClick={() => setState(1)}>
        hello
      </Button> */}
      <Box
        width={"100vw"}
        height={"100vh"}
        sx={{ display: "flex", justifyContent: "center", alignItems: "center" }}
      >
        <ConnectButton />
      </Box>
    </>
  );
}
